version: '3.7'
services:
  db:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: pltemplate
      POSTGRES_USER: pltemplate
      POSTGRES_DB: pltemplate
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  app:
    build:
      context: ./app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=pltemplate
      - DB_USER=pltemplate
      - DB_PASS=pltemplate
    volumes:
      - "./app:/usr/app"
    depends_on:
      db: 
        condition: service_healthy